"""Workspace scaffolding for `interspace init`.

Generates a working Interspace workspace at a chosen path: folder layout,
cross-platform self-locating launchers (.bat / .sh / .command), a brief
operator README, and optionally renders the bundled public sample so the
first launch shows a non-empty hub instead of an empty directory listing.

Launchers are self-locating (resolve their own directory at run-time, then
cd two levels up to the workspace root) so the workspace stays portable —
move or copy it, the launchers still work.

Surface:
    interspace init <workspace> [--port N] [--name NAME]
                                [--no-sample] [--force]

Exit codes:
    0  scaffolding succeeded
    1  refused (target exists and non-empty without --force)
    2  argument / filesystem error
"""

from __future__ import annotations

import json
import os
import shutil
import stat
import sys
from pathlib import Path
from typing import Iterable


# ----------------------------------------------------------------------
# Launcher templates
# ----------------------------------------------------------------------
#
# Self-locating: each template resolves its own directory at run-time and
# cd's two levels up (launcher lives at <ws>/local/launchers/<file>, so
# `../..` from there reaches the workspace root). Workspace is portable.
#
# Server invocation matches the existing convention:
#     python -m interspace serve local/rendered --port <port> --no-open --live
#
# Port-check idempotency guard: skip the spawn if something already listens
# on the chosen port. Lets the launcher be double-clicked repeatedly without
# stacking servers.

_BAT_TEMPLATE = """\
@echo off
rem Interspace launcher — auto-generated by `interspace init`.
rem Self-locating: %~dp0 is this file's directory; ..\\.. reaches the
rem workspace root regardless of where this launcher was invoked from.
cd /d "%~dp0\\..\\.."
rem PYTHONPATH points at the directory containing the `interspace` package
rem at init time, so `python -m interspace` resolves even when the workspace
rem is separate from the source checkout. Pip-installs override transparently.
set "PYTHONPATH={interspace_root};%PYTHONPATH%"
netstat -ano | findstr ":{port} " | findstr LISTENING >nul 2>&1
if errorlevel 1 (
    start "Interspace :{port}" /min python -m interspace serve local\\rendered --port {port} --no-open --live
    timeout /t 1 /nobreak >nul
)
start "" http://127.0.0.1:{port}/
exit /b 0
"""

_SH_TEMPLATE = """\
#!/usr/bin/env bash
# Interspace launcher — auto-generated by `interspace init` (Linux).
# Self-locating: walk up from $BASH_SOURCE to the workspace root, then
# the rest of the script is workspace-relative.
set -e
SCRIPT_DIR="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
cd "$SCRIPT_DIR/../.."
# Source location baked at init time so `python -m interspace` works from
# the workspace dir; harmless if interspace is pip-installed (site-packages
# wins for already-imported modules).
export PYTHONPATH="{interspace_root}:${{PYTHONPATH:-}}"
PORT={port}
if ! (ss -tln 2>/dev/null || netstat -tln 2>/dev/null) | grep -q ":$PORT "; then
    nohup python3 -m interspace serve local/rendered --port "$PORT" --no-open --live >/dev/null 2>&1 &
    sleep 1
fi
URL="http://127.0.0.1:$PORT/"
xdg-open "$URL" >/dev/null 2>&1 \\
    || open "$URL" >/dev/null 2>&1 \\
    || echo "Open $URL in your browser."
"""

_COMMAND_TEMPLATE = """\
#!/usr/bin/env bash
# Interspace launcher — auto-generated by `interspace init` (macOS).
# .command extension is Finder-double-clickable; `open` is macOS-native.
set -e
SCRIPT_DIR="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
cd "$SCRIPT_DIR/../.."
export PYTHONPATH="{interspace_root}:${{PYTHONPATH:-}}"
PORT={port}
if ! lsof -nP -iTCP:$PORT -sTCP:LISTEN >/dev/null 2>&1; then
    nohup python3 -m interspace serve local/rendered --port "$PORT" --no-open --live >/dev/null 2>&1 &
    sleep 1
fi
open "http://127.0.0.1:$PORT/"
"""


# ----------------------------------------------------------------------
# Workspace README content
# ----------------------------------------------------------------------

_WORKSPACE_README = """\
# Interspace workspace

Auto-generated by `interspace init` on {workspace_name}.

## Layout

```
{workspace_name}/
├── local/
│   ├── inputs/      ← put your *_input.json files here (adapter outputs
│   │                  or hand-curated JSON matching the Interspace schema)
│   ├── rendered/    ← `interspace render` outputs land here, one subdir
│   │                  per dataset. The local server serves this tree.
│   ├── launchers/   ← cross-platform launcher scripts (.bat / .sh /
│   │                  .command) — double-click to start the server and
│   │                  open the hub in your default browser.
│   └── adapters/    ← optional: operator-private adapters that read your
│                      own data and emit Interspace JSON. See upstream
│                      docs/ADAPTERS.md for the contract.
└── README.md        ← this file
```

## Launch

- Windows: double-click `local/launchers/{name}.bat`
- Linux:   `bash local/launchers/{name}.sh` (or make it executable + double-click in your file manager if it supports script execution)
- macOS:   double-click `local/launchers/{name}.command` (Finder runs it in Terminal)

The launcher starts `python -m interspace serve local/rendered --port {port}
--no-open --live` (idempotent — won't spawn a second server if port {port}
is already listening) and opens http://127.0.0.1:{port}/ in your default
browser.

## Adding your own data

1. Either write JSON by hand into `local/inputs/<name>_input.json` (small
   corpora — schema is in upstream `docs/INPUT_SCHEMA.md`) or write an
   adapter under `local/adapters/` that reads your data and outputs JSON.
2. Render: `python -m interspace render local/inputs/<name>_input.json -o local/rendered/<name>/`
3. Refresh the hub: `python -m interspace hub local/rendered/`
4. Reload the browser — your dataset appears as a new card on the hub.

For multi-source merging see `interspace merge` and the upstream
`docs/ADAPTERS.md`.

## Stopping the server

The server runs in a background process. To stop it:

- Windows: close the minimized `Interspace :{port}` console window, or
  `taskkill /F /IM python.exe` (kills all Python; surgical alternative is
  to use the PID shown by `netstat -ano | findstr ":{port} "`).
- Linux/macOS: `pkill -f "interspace serve"` or kill the PID from
  `lsof -nP -iTCP:{port} -sTCP:LISTEN`.
"""


# ----------------------------------------------------------------------
# Public entry point
# ----------------------------------------------------------------------

def init_workspace(
    workspace: Path,
    port: int = 8780,
    name: str = "interspace",
    include_sample: bool = True,
    force: bool = False,
) -> int:
    """Scaffold an Interspace workspace at `workspace`.

    Returns 0 on success, 1 if refused (non-empty target without --force),
    2 on filesystem error.
    """
    workspace = workspace.expanduser().resolve()

    if workspace.exists():
        if workspace.is_file():
            print(
                f"error: {workspace} is a file, not a directory",
                file=sys.stderr,
            )
            return 2
        if any(workspace.iterdir()) and not force:
            print(
                f"error: {workspace} exists and is non-empty (pass --force to scaffold over it)",
                file=sys.stderr,
            )
            return 1
    else:
        try:
            workspace.mkdir(parents=True)
        except OSError as e:
            print(f"error: could not create {workspace}: {e}", file=sys.stderr)
            return 2

    # Folder layout
    layout = [
        workspace / "local" / "inputs",
        workspace / "local" / "rendered",
        workspace / "local" / "launchers",
        workspace / "local" / "adapters",
    ]
    for d in layout:
        d.mkdir(parents=True, exist_ok=True)

    # Launchers (all three platforms, regardless of host). PYTHONPATH baked
    # at init time so the workspace doesn't need cwd == project root.
    launchers_dir = workspace / "local" / "launchers"
    interspace_root = _discover_interspace_root()
    _write_launcher_bat(launchers_dir / f"{name}.bat", port=port, interspace_root=interspace_root)
    _write_launcher_sh(launchers_dir / f"{name}.sh", port=port, interspace_root=interspace_root)
    _write_launcher_command(launchers_dir / f"{name}.command", port=port, interspace_root=interspace_root)

    # Workspace README
    readme_path = workspace / "README.md"
    readme_path.write_text(
        _WORKSPACE_README.format(
            workspace_name=workspace.name,
            name=name,
            port=port,
        ),
        encoding="utf-8",
    )

    # Optional sample seeding + render
    sample_msg = ""
    if include_sample:
        try:
            n_nodes = _seed_and_render_sample(workspace)
            sample_msg = f", seeded sample ({n_nodes} nodes)"
        except (FileNotFoundError, ValueError, OSError) as e:
            print(
                f"warning: sample seeding skipped ({e})",
                file=sys.stderr,
            )

    # Build initial hub only if something rendered (skip when --no-sample
    # leaves the rendered dir empty — hub would just print a no-renders error).
    rendered_dir = workspace / "local" / "rendered"
    if any((d / "_meta.json").is_file() for d in rendered_dir.iterdir() if d.is_dir()):
        try:
            from .hub import build_hub

            build_hub(rendered_dir)
        except Exception as e:  # noqa: BLE001 — hub-build failure shouldn't fail init
            print(f"warning: hub build skipped ({e})", file=sys.stderr)

    print(
        f"initialized Interspace workspace at {workspace}{sample_msg}",
        file=sys.stderr,
    )
    print(
        f"launch: {launchers_dir / (name + _platform_launcher_suffix())}",
        file=sys.stderr,
    )
    return 0


# ----------------------------------------------------------------------
# Launcher writers
# ----------------------------------------------------------------------

def _write_launcher_bat(path: Path, port: int, interspace_root: str) -> None:
    # CRLF line endings — bats expect them; `\r\n` keeps Windows happy when
    # the file is git-tracked with `* text=auto` defaults.
    content = _BAT_TEMPLATE.format(
        port=port, interspace_root=interspace_root
    ).replace("\n", "\r\n")
    path.write_text(content, encoding="utf-8")


def _write_launcher_sh(path: Path, port: int, interspace_root: str) -> None:
    path.write_text(
        _SH_TEMPLATE.format(port=port, interspace_root=interspace_root),
        encoding="utf-8",
    )
    _chmod_executable(path)


def _write_launcher_command(path: Path, port: int, interspace_root: str) -> None:
    path.write_text(
        _COMMAND_TEMPLATE.format(port=port, interspace_root=interspace_root),
        encoding="utf-8",
    )
    _chmod_executable(path)


def _discover_interspace_root() -> str:
    """The directory that contains the `interspace` package — used to seed
    PYTHONPATH in generated launchers so the workspace can be anywhere."""
    import interspace  # local re-import keeps installer importable standalone

    return str(Path(interspace.__file__).resolve().parent.parent)


def _chmod_executable(path: Path) -> None:
    """Add execute bits where the filesystem supports it. No-op on
    filesystems that don't carry POSIX modes (e.g. FAT32 / NTFS without
    perm passthrough); the file is still usable via `bash <script>`."""
    try:
        mode = path.stat().st_mode
        path.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    except OSError:
        pass


def _platform_launcher_suffix() -> str:
    if sys.platform.startswith("win"):
        return ".bat"
    if sys.platform == "darwin":
        return ".command"
    return ".sh"


# ----------------------------------------------------------------------
# Sample seeding
# ----------------------------------------------------------------------

def _seed_and_render_sample(workspace: Path) -> int:
    """Copy the public sample into the workspace and render it. Returns
    the sample's node count for the success message. Raises if the sample
    file isn't reachable from the running package."""
    sample_src = _locate_public_sample()
    if sample_src is None:
        raise FileNotFoundError("public sample (samples/example.json) not found")

    inputs_dir = workspace / "local" / "inputs"
    rendered_dir = workspace / "local" / "rendered"
    sample_dst = inputs_dir / "sample.json"
    shutil.copyfile(sample_src, sample_dst)

    from .generator import render_pages

    rc = render_pages(
        input_path=sample_dst,
        output_dir=rendered_dir / "sample",
        title="Sample",
    )
    if rc != 0:
        raise ValueError(f"render_pages returned {rc}")

    # Read node count back from the rendered _meta.json so the caller can
    # surface it in the success message.
    meta_path = rendered_dir / "sample" / "_meta.json"
    if meta_path.exists():
        try:
            return int(json.loads(meta_path.read_text(encoding="utf-8"))["nodes"])
        except (KeyError, ValueError, OSError):
            return 0
    return 0


def _locate_public_sample() -> Path | None:
    """Walk up from this file looking for `samples/example.json`. Works
    when Interspace is installed as a source checkout (typical) and when
    it's installed as a wheel that bundles samples/ alongside the package
    (future packaging direction)."""
    candidates: Iterable[Path] = (
        Path(__file__).parent / "samples" / "example.json",       # wheel bundle
        Path(__file__).parent.parent / "samples" / "example.json", # source checkout
    )
    for c in candidates:
        if c.is_file():
            return c
    return None
